if_red: True
is_record: False
if_show: False
if_pub: True
threshold: 20
exposure: 10
serial_name: /dev/ttyS5

#camera: 2213
CameraParams:
    cx: 296.147773
    cy: 243.416852
    fx: 419.784604
    fy: 420.409283
    distcoef1: -0.006569
    distcoef2: 0.012648
